# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Station.create([{ abbr: '12th', name: '12th St. Oakland' },
                { abbr: '16th', name: '16th St. Mission' },
                { abbr: '19th', name: '19th St. Oakland' },
                { abbr: '24th', name: '24th St. Mission' },
                { abbr: 'ashb', name: 'Ashby' },
                { abbr: 'balb', name: 'Balboa Park' },
                { abbr: 'bayf', name: 'Bay Fair' },
                { abbr: 'cast', name: 'Castro Valley' },
                { abbr: 'civc', name: 'Civic Center' },
                { abbr: 'cols', name: 'Coliseum' },
                { abbr: 'colm', name: 'Colma' },
                { abbr: 'conc', name: 'Concord' },
                { abbr: 'daly', name: 'Daly City' },
                { abbr: 'dbrk', name: 'Downtown Berkeley' },
                { abbr: 'dubl', name: 'Dublin/Pleasanton' },
                { abbr: 'deln', name: 'El Cerrito del Norte' },
                { abbr: 'plza', name: 'El Cerrito Plaza' },
                { abbr: 'embr', name: 'Embarcadero' },
                { abbr: 'frmt', name: 'Fremont' },
                { abbr: 'ftvl', name: 'Fruitvale' },
                { abbr: 'glen', name: 'Glen Park' },
                { abbr: 'hayw', name: 'Hayward' },
                { abbr: 'lafy', name: 'Lafayette' },
                { abbr: 'lake', name: 'Lake Merritt' },
                { abbr: 'mcar', name: 'MacArthur' },
                { abbr: 'mlbr', name: 'Millbrae' },
                { abbr: 'mont', name: 'Montgomery St.' },
                { abbr: 'nbrk', name: 'North Berkeley' },
                { abbr: 'ncon', name: 'North Concord/Martinez' },
                { abbr: 'orin', name: 'Orinda' },
                { abbr: 'pitt', name: 'Pittsburg/Bay Point' },
                { abbr: 'phil', name: 'Pleasant Hill' },
                { abbr: 'powl', name: 'Powell St.' },
                { abbr: 'rich', name: 'Richmond' },
                { abbr: 'rock', name: 'Rockridge' },
                { abbr: 'sbrn', name: 'San Bruno' },
                { abbr: 'sfia', name: 'San Francisco Intl Airport' },
                { abbr: 'sanl', name: 'San Leandro' },
                { abbr: 'shay', name: 'South Hayward' },
                { abbr: 'ssan', name: 'South San Francisco' },
                { abbr: 'ucty', name: 'Union City' },
                { abbr: 'wcrk', name: 'Walnut Creek' },
                { abbr: 'wdub', name: 'West Dublin/Pleasanton' },
                { abbr: 'woak', name: 'West Oakland' },
                { abbr: 'oakl', name: 'Oakland Int’l Airport' }])
